In [32]:
import pandas as pd
from factor_analyzer import FactorAnalyzer
from sklearn.preprocessing import scale
import numpy as np

In [21]:
df = pd.read_excel('C:/Users/jxjsj/Desktop/stat.xlsx')
# 标准化
df = df.apply(lambda x: (x-x.mean())/x.std())

In [62]:
factorA = FactorAnalyzer(n_factors=3, rotation='varimax')
result = factorA.fit(df)

In [54]:
# 原始数据中变量的相关系数矩阵
result.corr_

array([[ 1.        ,  0.68426334,  0.87681744,  0.64436027,  0.79532736,
         0.84444176,  0.89655271,  0.80735834, -0.02305626, -0.12250821,
        -0.08201421, -0.0173678 ],
       [ 0.68426334,  1.        ,  0.78957935,  0.41704238,  0.91898038,
         0.81086658,  0.63389862,  0.74750326,  0.21823394,  0.35009193,
         0.42329181,  0.31370632],
       [ 0.87681744,  0.78957935,  1.        ,  0.44212847,  0.80712059,
         0.77788284,  0.73836089,  0.71557956,  0.05249843, -0.06721818,
         0.00312035,  0.01439222],
       [ 0.64436027,  0.41704238,  0.44212847,  1.        ,  0.6768951 ,
         0.81869576,  0.89028653,  0.89604931, -0.16561155,  0.06337018,
         0.0256761 ,  0.07952518],
       [ 0.79532736,  0.91898038,  0.80712059,  0.6768951 ,  1.        ,
         0.942741  ,  0.81075293,  0.90250783,  0.13492558,  0.22998857,
         0.27772687,  0.20342811],
       [ 0.84444176,  0.81086658,  0.77788284,  0.81869576,  0.942741  ,
         1.        ,  

In [24]:
# 因子载荷矩阵
result.loadings_

array([[ 0.90531087, -0.15225049,  0.19079485],
       [ 0.87139013,  0.38457394, -0.10787238],
       [ 0.9360332 , -0.08119196, -0.08273553],
       [ 0.5614854 ,  0.03053045,  0.8134536 ],
       [ 0.92028851,  0.24360342,  0.15767616],
       [ 0.89128253,  0.18168038,  0.3857656 ],
       [ 0.8193446 ,  0.01386398,  0.5243    ],
       [ 0.83054964,  0.18897   ,  0.51937831],
       [ 0.08259912,  0.31519302, -0.2713622 ],
       [ 0.00718101,  0.91728153,  0.02652618],
       [ 0.06555422,  0.99462143, -0.06233647],
       [ 0.0734607 ,  0.61423912,  0.08141473]])

In [25]:
# 每个变量的公共度：因子系数的平方和
result.get_communalities()

array([0.87917066, 0.91885432, 0.88959545, 0.97790472, 0.93113533,
       0.9762074 , 0.94640827, 0.9952762 , 0.1798067 , 0.84216061,
       0.99745499, 0.38931452])

In [27]:
# 特征根
result.get_eigenvalues()

(array([6.67065775e+00, 2.67513163e+00, 1.10682423e+00, 6.69757362e-01,
        4.37086405e-01, 2.29113795e-01, 7.57675066e-02, 7.34795258e-02,
        3.16757532e-02, 2.14931937e-02, 6.68665432e-03, 2.32618875e-03]),
 array([ 6.60776155e+00,  2.46824856e+00,  8.48293258e-01,  1.49279527e-01,
         1.36129001e-01,  8.79859879e-03,  8.86786347e-04, -4.05967978e-03,
        -3.16017006e-02, -5.55781456e-02, -6.56924235e-02, -1.39176164e-01]))

In [35]:
# 第三行，因子对应主成分的累积方差贡献度
result.get_factor_variance()

(array([5.78935429, 2.61416735, 1.51976752]),
 array([0.48244619, 0.21784728, 0.12664729]),
 array([0.48244619, 0.70029347, 0.82694076]))

In [83]:
# 因子得分
result.transform(df)

array([[ 1.83451282,  0.05594922,  5.32810184],
       [ 1.16825881, -0.16615848, -0.33412618],
       [-0.38691636, -0.4938628 ,  0.10637513],
       [-0.20157693, -0.09670432, -0.51060111],
       [-0.8033556 ,  0.01621128, -0.17915596],
       [-0.01779882, -0.17005665,  0.13808952],
       [-0.2441982 , -0.03358529,  0.08150822],
       [-0.03951841, -0.43818282,  0.51732477],
       [ 4.42467803,  0.3054275 , -2.04627643],
       [-0.08508557,  0.18397899,  0.02225295],
       [ 0.12275315, -0.39221754, -0.10713605],
       [-0.84651438,  1.02150997, -0.05744757],
       [-0.29503813, -0.28721899, -0.35685344],
       [-0.63231435,  0.06089832,  0.00581223],
       [-0.25621418,  0.19943473, -0.05613159],
       [-0.35267987, -0.51824886, -0.07819239],
       [ 0.15116537, -0.65228223,  0.26036902],
       [-0.48552522,  0.00974283,  0.01856252],
       [ 1.36595365,  0.88170517,  0.26819095],
       [-0.69569398, -0.03531591, -0.05026641],
       [-0.91853759, -0.36644509,  0.061

In [84]:
# 因子得分系数矩阵
import statsmodels.api as sm
factor_score_list = []
for factor in range(result.transform(df).shape[1]):
    est = sm.OLS(result.transform(df)[:,factor],df)
    result_ = est.fit()
    factor_score_list.append(list(result_.params))
factor_score_matrix = np.array(factor_score_list).T
factor_score_matrix

array([[-0.14010556,  0.35740889,  0.83459161],
       [-0.00359464, -0.37171779,  0.0363167 ],
       [ 0.10325015, -0.46879358, -0.04480587],
       [-0.8330285 , -1.35574385,  1.65423407],
       [ 0.56140771, -0.23024732, -1.34369377],
       [ 0.01709702, -0.9818414 , -0.05008082],
       [ 0.71912219, -0.85651474, -1.83646883],
       [ 0.47323014,  3.58733196,  1.35512298],
       [-0.02506216, -0.12778413,  0.03971773],
       [-0.10278111,  0.15038908,  0.33558781],
       [-0.06387537,  0.97443494, -0.15352667],
       [-0.0683058 , -0.36722362, -0.01882904]])